### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [haitaim/hip-fellow#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by haitaim** [comment]
I'm honestly shocked that you managed to find this repo, but I digress. If there's any content that you'd like changed with the current screenshot, please let me know.
